backend:
  name: github
  repo: wylieisdbald/wylieisdbald.github.io   # Path to your GitHub repository
  branch: main          # Branch to update (optional; defaults to main)

# This line should *not* be indented
media_folder: "media"

# These lines should *not* be indented
collections:
  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
